#!/bin/bash
set -e

ARCH=${ARCH:?"ARCH not set"}

source $(dirname $0)/version

cd $(dirname $0)/..

if [ ! -e bin/rancher-cni-ipam ]; then
    ./scripts/build
fi

FILE_NAME="rancher-cni-ipam-${VERSION}-${ARCH}.tar.gz"

mkdir -p dist/artifacts
cd bin/
tar cvzf ../dist/artifacts/$FILE_NAME .
shasum -a 256 ../dist/artifacts/$FILE_NAME | awk '{print $1}' > ../dist/artifacts/$FILE_NAME.sha256
